eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}

spring:
  zipkin:
    base-url: http://localhost:9411 

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints, including Prometheus metrics
  metrics:
    export:
      prometheus:
        enabled: true  # Enable Prometheus metrics
  endpoint:
    prometheus:
      enabled: true  # Enable Prometheus endpoint
